name: "FRP Client"
version: "2025.07.23.0"
slug: "frpc"
description: "快速内网穿透客户端，专为国内用户优化（支持 Gitee 镜像加速）"
url: "https://github.com/sunboss/ha-frpc-addon"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
startup: application
boot: auto
init: false
options:
  server_addr: ""
  server_port: 7000
  token: ""
  local_port: 8123
  proxy_name: "ha_proxy"
  proxy_type: "http"
  admin_port: 7500
  admin_user: ""
  admin_pwd: ""
schema:
  server_addr: str
  server_port: int
  token: str?
  local_port: int
  proxy_name: str
  proxy_type: "selector(http|tcp|udp|stcp|xtcp|sudp)"
  admin_port: int?
  admin_user: str?
  admin_pwd: str?
map:
  - share:rw
ports:
  7500/tcp: 7500
image: "ghcr.io/sunboss/ha-frpc-addon-{arch}"
